export default {
  rowlist: {
    margin: "50px",
    display: "table",
    clear: "both",
    maxWidth: "400px",
    minHeight: "680px",
    backgroundImage: " radial-gradient(#1a1919 4.2%, transparent 0)",
    backgroundSize: "40px 40px",
    width: "33.33%",
    backgroundColor: "#41403a",
    boxShadow: "4px 3px 7px 2px #00000040",
    padding: "15px",
    borderRadius: "20px",
    float: "left",
    position: "relative",
  },
  Inp: {
    border: "0",
    padding: "0px 50px",
    width: "200px",
    height: " 50px",
    fontSize: "18px",
    borderRadius: "0px",
    margin: "20px",
    position: "none",
  },
  btn: {
    height: "50px",
    width: "70px",
    border: "0",
    borderRadius: "5px",
    backgroundColor: " #e28120",
    fontWeight: "bolder",
    color: "#fff",
    cursor: "pointer",
  },
};
